# -*- coding: utf-8 -*-
"""สิรภพ Lab 3 ทำข้อมูลให้เป็นภาพ

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g2lt0S4CnGoRZ5tZFcHMmTwcglN8yacB

# Install all package
Run all cell press : `Ctrl+F9` or `Runtime > Run all`

# And Merge 2 Data
"""

import pandas as pd
import matplotlib.pyplot as plt # New package for make graph

Url = "https://github.com/comsciyorwor5/comsci/raw/master/Data1.csv"
Url2 = "https://github.com/comsciyorwor5/comsci/raw/master/Data2.csv"

Data = pd.read_csv(Url)
Data2 = pd.read_csv(Url2)

MergeData = Data.merge(Data2)
print(MergeData)

"""# Histogram graph"""

MergeData.Weight.hist(range=[60,80],bins=10)

plt.title('Weight Frequency')         # Name
plt.xlabel('Weight')                  # X Name
plt.ylabel('Frequency')               # Y Name
plt.axis([60,80,0,10])                # Range Show X in range 60-80 , Y in range 0-10
plt.xticks(range(60,81,2))            # Line a grid in X range 60-80 every 2 Weight
plt.show                              # Display graph